### ISSUE TITLE
Test ArchieML with Arabic

### ISSUE THREAD

**Issue by adrian-the-git** [BeautifulTrouble/BeautifulRisingMeta#1]

**Comment by adrian-the-git** [comment]
And it works! (I'm actually just testing how the milestones correlate with issues, but the part about RTL text is true. Arabic and ArchieML play together just fine.)

**Comment by phillipadsmith** [comment]
> And it works! (I'm actually just testing how the milestones correlate with issues, but the part about RTL text is true. Arabic and ArchieML play together just fine.)

Huzzah! :-)
